version: 2

models:
  - name: int_commandes_clients
    description: "Vue analytique des commandes enrichies avec les clients"
    columns:
      - name: commande_id
        description: "Identifiant unique de la commande"
        tests:
          - not_null
          - unique

      - name: client_id
        description: "Identifiant du client"
        tests:
          - not_null

      - name: nom
        description: "Nom du client"

      - name: prenom
        description: "Prénom du client"

      - name: date_commande
        description: "Date de la commande"

      - name: montant_total
        description: "Montant total de la commande"
        tests:
          - not_null
